// Auth
export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

// Article
export const ARTICLE_REQUEST = "ARTICLE_REQUEST";
export const ARTICLE_SUCCESS = "ARTICLE_SUCCESS";
export const ARTICLE_ERROR = "ARTICLE_ERROR";
export const ARTICLELIST_REQUEST = "ARTICLELIST_REQUEST";
export const ARTICLELIST_SUCCESS = "ARTICLELIST_SUCCESS";
export const ARTICLELIST_ERROR = "ARTICLELIST_SUCCESS";
